const Types = {
  SAVE_USER_ID: 'test/SAVE_USER_ID',
  SAVE_LANGUAGE_TITLE: 'test/SAVE_LANGUAGE_TITLE',
  SAVE_ALL_QUESTION_COUNT: 'test/SAVE_ALL_QUESTION_COUNT',
  SAVE_CURRENT_QUESTION: 'test/SAVE_CURRENT_QUESTION',
  SAVE_RESULT_ANSWER: 'test/SAVE_RESULT_ANSWER',
  SAVE_FINISH_TIME: 'test/SAVE_FINISH_TIME',
  SAVE_FINISH_ANSWERS_AND_QUESTIONS_RESULT:
    'test/SAVE_FINISH_ANSWERS_AND_QUESTIONS_RESULT',
  SAVE_ERROR: 'test/SAVE_ERROR',
};

export default Types;
