export default {
    FETCH_TESTS_REQUEST: 'FETCH_TESTS_REQUEST',
    FETCH_TESTS_SUCCESS: 'FETCH_TESTS_SUCCESS',
    FETCH_TESTS_ERROR: 'FETCH_TESTS_ERROR',
    // LOADER_ON: 'LOADER_ON',
    // LOADER_OFF: 'LOADER_OFF'
}